# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sci_tool.ui'
#
# Created: Thu Jul 23 13:29:09 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.maintabwidget = QtGui.QTabWidget(self.centralwidget)
        self.maintabwidget.setObjectName(_fromUtf8("maintabwidget"))
        self.scitooltab = QtGui.QWidget()
        self.scitooltab.setObjectName(_fromUtf8("scitooltab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.scitooltab)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.distext = QtGui.QTabWidget(self.scitooltab)
        self.distext.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distext.sizePolicy().hasHeightForWidth())
        self.distext.setSizePolicy(sizePolicy)
        self.distext.setMaximumSize(QtCore.QSize(194, 16777215))
        self.distext.setTabPosition(QtGui.QTabWidget.North)
        self.distext.setTabShape(QtGui.QTabWidget.Triangular)
        self.distext.setUsesScrollButtons(True)
        self.distext.setTabsClosable(False)
        self.distext.setMovable(False)
        self.distext.setObjectName(_fromUtf8("distext"))
        self.dishextext = QtGui.QWidget()
        self.dishextext.setMouseTracking(False)
        self.dishextext.setObjectName(_fromUtf8("dishextext"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dishextext)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.dishex = QtGui.QPlainTextEdit(self.dishextext)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.dishex.setFont(font)
        self.dishex.setReadOnly(True)
        self.dishex.setObjectName(_fromUtf8("dishex"))
        self.verticalLayout_7.addWidget(self.dishex)
        self.distext.addTab(self.dishextext, _fromUtf8(""))
        self.disstringtext = QtGui.QWidget()
        self.disstringtext.setObjectName(_fromUtf8("disstringtext"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.disstringtext)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.distring = QtGui.QPlainTextEdit(self.disstringtext)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.distring.setFont(font)
        self.distring.setReadOnly(True)
        self.distring.setObjectName(_fromUtf8("distring"))
        self.verticalLayout_10.addWidget(self.distring)
        self.distext.addTab(self.disstringtext, _fromUtf8(""))
        self.Protocoltab = QtGui.QWidget()
        self.Protocoltab.setObjectName(_fromUtf8("Protocoltab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Protocoltab)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox = QtGui.QCheckBox(self.Protocoltab)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.label = QtGui.QLabel(self.Protocoltab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.framehead_edit = QtGui.QLineEdit(self.Protocoltab)
        self.framehead_edit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.framehead_edit.setMaxLength(2)
        self.framehead_edit.setCursorPosition(2)
        self.framehead_edit.setObjectName(_fromUtf8("framehead_edit"))
        self.horizontalLayout_2.addWidget(self.framehead_edit)
        self.label_2 = QtGui.QLabel(self.Protocoltab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.framenum_edit = QtGui.QLineEdit(self.Protocoltab)
        self.framenum_edit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.framenum_edit.setObjectName(_fromUtf8("framenum_edit"))
        self.horizontalLayout_2.addWidget(self.framenum_edit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.framesumcheck = QtGui.QCheckBox(self.Protocoltab)
        self.framesumcheck.setChecked(True)
        self.framesumcheck.setObjectName(_fromUtf8("framesumcheck"))
        self.horizontalLayout_8.addWidget(self.framesumcheck)
        self.label_3 = QtGui.QLabel(self.Protocoltab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.framend_edit = QtGui.QLineEdit(self.Protocoltab)
        self.framend_edit.setObjectName(_fromUtf8("framend_edit"))
        self.horizontalLayout_8.addWidget(self.framend_edit)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.disprotocol = QtGui.QPlainTextEdit(self.Protocoltab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.disprotocol.setFont(font)
        self.disprotocol.setReadOnly(True)
        self.disprotocol.setObjectName(_fromUtf8("disprotocol"))
        self.verticalLayout_5.addWidget(self.disprotocol)
        self.distext.addTab(self.Protocoltab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.distext)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.clrcontentbutton = QtGui.QPushButton(self.scitooltab)
        self.clrcontentbutton.setObjectName(_fromUtf8("clrcontentbutton"))
        self.horizontalLayout_16.addWidget(self.clrcontentbutton)
        self.savecontentbutton = QtGui.QPushButton(self.scitooltab)
        self.savecontentbutton.setObjectName(_fromUtf8("savecontentbutton"))
        self.horizontalLayout_16.addWidget(self.savecontentbutton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.line_6 = QtGui.QFrame(self.scitooltab)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_3.addWidget(self.line_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.portlabel = QtGui.QLabel(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portlabel.sizePolicy().hasHeightForWidth())
        self.portlabel.setSizePolicy(sizePolicy)
        self.portlabel.setMinimumSize(QtCore.QSize(60, 0))
        self.portlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.portlabel.setFont(font)
        self.portlabel.setObjectName(_fromUtf8("portlabel"))
        self.horizontalLayout_4.addWidget(self.portlabel)
        spacerItem = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lineEdit = QtGui.QLineEdit(self.scitooltab)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.portcomtext = QtGui.QLineEdit(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portcomtext.sizePolicy().hasHeightForWidth())
        self.portcomtext.setSizePolicy(sizePolicy)
        self.portcomtext.setMinimumSize(QtCore.QSize(35, 25))
        self.portcomtext.setMaximumSize(QtCore.QSize(40, 16777215))
        self.portcomtext.setMaxLength(2)
        self.portcomtext.setFrame(True)
        self.portcomtext.setEchoMode(QtGui.QLineEdit.Normal)
        self.portcomtext.setAlignment(QtCore.Qt.AlignCenter)
        self.portcomtext.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.portcomtext.setObjectName(_fromUtf8("portcomtext"))
        self.horizontalLayout_4.addWidget(self.portcomtext)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bandratelabel = QtGui.QLabel(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandratelabel.sizePolicy().hasHeightForWidth())
        self.bandratelabel.setSizePolicy(sizePolicy)
        self.bandratelabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bandratelabel.setFont(font)
        self.bandratelabel.setObjectName(_fromUtf8("bandratelabel"))
        self.horizontalLayout_3.addWidget(self.bandratelabel)
        spacerItem1 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.baudratecombo = QtGui.QComboBox(self.scitooltab)
        self.baudratecombo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudratecombo.sizePolicy().hasHeightForWidth())
        self.baudratecombo.setSizePolicy(sizePolicy)
        self.baudratecombo.setMinimumSize(QtCore.QSize(0, 25))
        self.baudratecombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.baudratecombo.setBaseSize(QtCore.QSize(0, 0))
        self.baudratecombo.setEditable(False)
        self.baudratecombo.setObjectName(_fromUtf8("baudratecombo"))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.baudratecombo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.databitlabel = QtGui.QLabel(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databitlabel.sizePolicy().hasHeightForWidth())
        self.databitlabel.setSizePolicy(sizePolicy)
        self.databitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.databitlabel.setFont(font)
        self.databitlabel.setObjectName(_fromUtf8("databitlabel"))
        self.horizontalLayout_5.addWidget(self.databitlabel)
        spacerItem2 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.databitcombo = QtGui.QComboBox(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databitcombo.sizePolicy().hasHeightForWidth())
        self.databitcombo.setSizePolicy(sizePolicy)
        self.databitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.databitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.databitcombo.setObjectName(_fromUtf8("databitcombo"))
        self.databitcombo.addItem(_fromUtf8(""))
        self.databitcombo.addItem(_fromUtf8(""))
        self.databitcombo.addItem(_fromUtf8(""))
        self.databitcombo.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.databitcombo)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkbitlabel = QtGui.QLabel(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbitlabel.sizePolicy().hasHeightForWidth())
        self.checkbitlabel.setSizePolicy(sizePolicy)
        self.checkbitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkbitlabel.setFont(font)
        self.checkbitlabel.setObjectName(_fromUtf8("checkbitlabel"))
        self.horizontalLayout_6.addWidget(self.checkbitlabel)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.checkbitcombo = QtGui.QComboBox(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbitcombo.sizePolicy().hasHeightForWidth())
        self.checkbitcombo.setSizePolicy(sizePolicy)
        self.checkbitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.checkbitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.checkbitcombo.setObjectName(_fromUtf8("checkbitcombo"))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.checkbitcombo)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.stopbitlabel = QtGui.QLabel(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitlabel.sizePolicy().hasHeightForWidth())
        self.stopbitlabel.setSizePolicy(sizePolicy)
        self.stopbitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopbitlabel.setFont(font)
        self.stopbitlabel.setObjectName(_fromUtf8("stopbitlabel"))
        self.horizontalLayout_7.addWidget(self.stopbitlabel)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.stopbitcombo = QtGui.QComboBox(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitcombo.sizePolicy().hasHeightForWidth())
        self.stopbitcombo.setSizePolicy(sizePolicy)
        self.stopbitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.stopbitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.stopbitcombo.setObjectName(_fromUtf8("stopbitcombo"))
        self.stopbitcombo.addItem(_fromUtf8(""))
        self.stopbitcombo.addItem(_fromUtf8(""))
        self.stopbitcombo.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.stopbitcombo)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.sciopenButton = QtGui.QPushButton(self.scitooltab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sciopenButton.sizePolicy().hasHeightForWidth())
        self.sciopenButton.setSizePolicy(sizePolicy)
        self.sciopenButton.setMaximumSize(QtCore.QSize(194, 16777215))
        self.sciopenButton.setCheckable(True)
        self.sciopenButton.setChecked(False)
        self.sciopenButton.setObjectName(_fromUtf8("sciopenButton"))
        self.verticalLayout.addWidget(self.sciopenButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.debugtab = QtGui.QTabWidget(self.scitooltab)
        self.debugtab.setTabShape(QtGui.QTabWidget.Triangular)
        self.debugtab.setObjectName(_fromUtf8("debugtab"))
        self.sendtab = QtGui.QWidget()
        self.sendtab.setObjectName(_fromUtf8("sendtab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.sendtab)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.sendclr_Button = QtGui.QPushButton(self.sendtab)
        self.sendclr_Button.setObjectName(_fromUtf8("sendclr_Button"))
        self.horizontalLayout_9.addWidget(self.sendclr_Button)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.label_10 = QtGui.QLabel(self.sendtab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.char_radioButton = QtGui.QRadioButton(self.sendtab)
        self.char_radioButton.setObjectName(_fromUtf8("char_radioButton"))
        self.horizontalLayout_9.addWidget(self.char_radioButton)
        self.hex_radioButton = QtGui.QRadioButton(self.sendtab)
        self.hex_radioButton.setAcceptDrops(False)
        self.hex_radioButton.setChecked(True)
        self.hex_radioButton.setObjectName(_fromUtf8("hex_radioButton"))
        self.horizontalLayout_9.addWidget(self.hex_radioButton)
        self.mainsend_Button = QtGui.QPushButton(self.sendtab)
        self.mainsend_Button.setObjectName(_fromUtf8("mainsend_Button"))
        self.horizontalLayout_9.addWidget(self.mainsend_Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.mainsend_Edit = QtGui.QTextEdit(self.sendtab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.mainsend_Edit.setFont(font)
        self.mainsend_Edit.setObjectName(_fromUtf8("mainsend_Edit"))
        self.verticalLayout_8.addWidget(self.mainsend_Edit)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.line_2 = QtGui.QFrame(self.sendtab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_9.addWidget(self.line_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_4 = QtGui.QLabel(self.sendtab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.cmd1_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd1_Edit.sizePolicy().hasHeightForWidth())
        self.cmd1_Edit.setSizePolicy(sizePolicy)
        self.cmd1_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cmd1_Edit.setFont(font)
        self.cmd1_Edit.setObjectName(_fromUtf8("cmd1_Edit"))
        self.horizontalLayout_11.addWidget(self.cmd1_Edit)
        self.cmd1sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd1sned_Button.setObjectName(_fromUtf8("cmd1sned_Button"))
        self.horizontalLayout_11.addWidget(self.cmd1sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.line = QtGui.QFrame(self.sendtab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_9.addWidget(self.line)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_5 = QtGui.QLabel(self.sendtab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.cmd2_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd2_Edit.sizePolicy().hasHeightForWidth())
        self.cmd2_Edit.setSizePolicy(sizePolicy)
        self.cmd2_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cmd2_Edit.setFont(font)
        self.cmd2_Edit.setObjectName(_fromUtf8("cmd2_Edit"))
        self.horizontalLayout_12.addWidget(self.cmd2_Edit)
        self.cmd2sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd2sned_Button.setObjectName(_fromUtf8("cmd2sned_Button"))
        self.horizontalLayout_12.addWidget(self.cmd2sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.line_3 = QtGui.QFrame(self.sendtab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_9.addWidget(self.line_3)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_6 = QtGui.QLabel(self.sendtab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.cmd3_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd3_Edit.sizePolicy().hasHeightForWidth())
        self.cmd3_Edit.setSizePolicy(sizePolicy)
        self.cmd3_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cmd3_Edit.setFont(font)
        self.cmd3_Edit.setObjectName(_fromUtf8("cmd3_Edit"))
        self.horizontalLayout_13.addWidget(self.cmd3_Edit)
        self.cmd3sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd3sned_Button.setObjectName(_fromUtf8("cmd3sned_Button"))
        self.horizontalLayout_13.addWidget(self.cmd3sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.line_4 = QtGui.QFrame(self.sendtab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_9.addWidget(self.line_4)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_7 = QtGui.QLabel(self.sendtab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_14.addWidget(self.label_7)
        self.cmd4_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd4_Edit.sizePolicy().hasHeightForWidth())
        self.cmd4_Edit.setSizePolicy(sizePolicy)
        self.cmd4_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cmd4_Edit.setFont(font)
        self.cmd4_Edit.setObjectName(_fromUtf8("cmd4_Edit"))
        self.horizontalLayout_14.addWidget(self.cmd4_Edit)
        self.cmd4sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd4sned_Button.setObjectName(_fromUtf8("cmd4sned_Button"))
        self.horizontalLayout_14.addWidget(self.cmd4sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.line_5 = QtGui.QFrame(self.sendtab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_9.addWidget(self.line_5)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_8 = QtGui.QLabel(self.sendtab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_15.addWidget(self.label_8)
        self.cmd5_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd5_Edit.sizePolicy().hasHeightForWidth())
        self.cmd5_Edit.setSizePolicy(sizePolicy)
        self.cmd5_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cmd5_Edit.setFont(font)
        self.cmd5_Edit.setObjectName(_fromUtf8("cmd5_Edit"))
        self.horizontalLayout_15.addWidget(self.cmd5_Edit)
        self.cmd5sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd5sned_Button.setObjectName(_fromUtf8("cmd5sned_Button"))
        self.horizontalLayout_15.addWidget(self.cmd5sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_9.setStretch(5, 1)
        self.verticalLayout_9.setStretch(7, 1)
        self.verticalLayout_9.setStretch(9, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 1)
        self.debugtab.addTab(self.sendtab, _fromUtf8(""))
        self.debugdatatab = QtGui.QWidget()
        self.debugdatatab.setObjectName(_fromUtf8("debugdatatab"))
        self.debugtab.addTab(self.debugdatatab, _fromUtf8(""))
        self.matplottab = QtGui.QWidget()
        self.matplottab.setObjectName(_fromUtf8("matplottab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.matplottab)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.Dataplot1 = QtGui.QHBoxLayout()
        self.Dataplot1.setSpacing(1)
        self.Dataplot1.setObjectName(_fromUtf8("Dataplot1"))
        self.verticalLayout_6.addLayout(self.Dataplot1)
        self.Dataplot2 = QtGui.QHBoxLayout()
        self.Dataplot2.setSpacing(1)
        self.Dataplot2.setObjectName(_fromUtf8("Dataplot2"))
        self.verticalLayout_6.addLayout(self.Dataplot2)
        self.Dataplot3 = QtGui.QHBoxLayout()
        self.Dataplot3.setSpacing(1)
        self.Dataplot3.setObjectName(_fromUtf8("Dataplot3"))
        self.verticalLayout_6.addLayout(self.Dataplot3)
        self.debugtab.addTab(self.matplottab, _fromUtf8(""))
        self.motortab = QtGui.QWidget()
        self.motortab.setObjectName(_fromUtf8("motortab"))
        self.debugtab.addTab(self.motortab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.debugtab)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.maintabwidget.addTab(self.scitooltab, _fromUtf8(""))
        self.about_tab = QtGui.QWidget()
        self.about_tab.setObjectName(_fromUtf8("about_tab"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.about_tab)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.textBrowser = QtGui.QTextBrowser(self.about_tab)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayout_10.addWidget(self.textBrowser)
        self.maintabwidget.addTab(self.about_tab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.maintabwidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.maintabwidget.setCurrentIndex(0)
        self.distext.setCurrentIndex(0)
        self.baudratecombo.setCurrentIndex(16)
        self.debugtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DebugTool@nixianmin", None))
        self.distext.setTabText(self.distext.indexOf(self.dishextext), _translate("MainWindow", "Hex", None))
        self.distext.setTabText(self.distext.indexOf(self.disstringtext), _translate("MainWindow", "String", None))
        self.checkBox.setText(_translate("MainWindow", "使能", None))
        self.label.setText(_translate("MainWindow", "帧头：", None))
        self.framehead_edit.setInputMask(_translate("MainWindow", "HH; ", None))
        self.framehead_edit.setText(_translate("MainWindow", "FF", None))
        self.label_2.setText(_translate("MainWindow", "数据：", None))
        self.framenum_edit.setInputMask(_translate("MainWindow", "99; ", None))
        self.framenum_edit.setText(_translate("MainWindow", "4", None))
        self.framesumcheck.setText(_translate("MainWindow", "和校验", None))
        self.label_3.setText(_translate("MainWindow", "帧尾：", None))
        self.framend_edit.setInputMask(_translate("MainWindow", "HH; ", None))
        self.framend_edit.setText(_translate("MainWindow", "FF", None))
        self.distext.setTabText(self.distext.indexOf(self.Protocoltab), _translate("MainWindow", "Protocol", None))
        self.clrcontentbutton.setText(_translate("MainWindow", "清除内容", None))
        self.savecontentbutton.setText(_translate("MainWindow", "另存为", None))
        self.portlabel.setText(_translate("MainWindow", "端口号：", None))
        self.lineEdit.setText(_translate("MainWindow", "Com Port", None))
        self.portcomtext.setInputMask(_translate("MainWindow", "99; ", None))
        self.portcomtext.setText(_translate("MainWindow", "3", None))
        self.bandratelabel.setText(_translate("MainWindow", "波特率：", None))
        self.baudratecombo.setItemText(0, _translate("MainWindow", "50", None))
        self.baudratecombo.setItemText(1, _translate("MainWindow", "75", None))
        self.baudratecombo.setItemText(2, _translate("MainWindow", "110", None))
        self.baudratecombo.setItemText(3, _translate("MainWindow", "134", None))
        self.baudratecombo.setItemText(4, _translate("MainWindow", "150", None))
        self.baudratecombo.setItemText(5, _translate("MainWindow", "200", None))
        self.baudratecombo.setItemText(6, _translate("MainWindow", "300", None))
        self.baudratecombo.setItemText(7, _translate("MainWindow", "600", None))
        self.baudratecombo.setItemText(8, _translate("MainWindow", "1200", None))
        self.baudratecombo.setItemText(9, _translate("MainWindow", "1800", None))
        self.baudratecombo.setItemText(10, _translate("MainWindow", "2400", None))
        self.baudratecombo.setItemText(11, _translate("MainWindow", "4800", None))
        self.baudratecombo.setItemText(12, _translate("MainWindow", "9600", None))
        self.baudratecombo.setItemText(13, _translate("MainWindow", "19200", None))
        self.baudratecombo.setItemText(14, _translate("MainWindow", "38400", None))
        self.baudratecombo.setItemText(15, _translate("MainWindow", "57600", None))
        self.baudratecombo.setItemText(16, _translate("MainWindow", "115200", None))
        self.databitlabel.setText(_translate("MainWindow", "数据位：", None))
        self.databitcombo.setItemText(0, _translate("MainWindow", "8bit", None))
        self.databitcombo.setItemText(1, _translate("MainWindow", "7bit", None))
        self.databitcombo.setItemText(2, _translate("MainWindow", "6bit", None))
        self.databitcombo.setItemText(3, _translate("MainWindow", "5bit", None))
        self.checkbitlabel.setText(_translate("MainWindow", "校验位：", None))
        self.checkbitcombo.setItemText(0, _translate("MainWindow", "None无", None))
        self.checkbitcombo.setItemText(1, _translate("MainWindow", "Even偶", None))
        self.checkbitcombo.setItemText(2, _translate("MainWindow", "Odd奇", None))
        self.checkbitcombo.setItemText(3, _translate("MainWindow", "Mark1", None))
        self.checkbitcombo.setItemText(4, _translate("MainWindow", "Space0", None))
        self.stopbitlabel.setText(_translate("MainWindow", "停止位：", None))
        self.stopbitcombo.setItemText(0, _translate("MainWindow", "1bit", None))
        self.stopbitcombo.setItemText(1, _translate("MainWindow", "1.5bit", None))
        self.stopbitcombo.setItemText(2, _translate("MainWindow", "2bit", None))
        self.sciopenButton.setText(_translate("MainWindow", "打开", None))
        self.sendclr_Button.setText(_translate("MainWindow", "清空数据", None))
        self.label_10.setText(_translate("MainWindow", "数据格式:", None))
        self.char_radioButton.setText(_translate("MainWindow", "Char", None))
        self.hex_radioButton.setText(_translate("MainWindow", "Hex", None))
        self.mainsend_Button.setText(_translate("MainWindow", "发送", None))
        self.label_4.setText(_translate("MainWindow", "CMD1:", None))
        self.cmd1sned_Button.setText(_translate("MainWindow", "发送", None))
        self.label_5.setText(_translate("MainWindow", "CMD2:", None))
        self.cmd2sned_Button.setText(_translate("MainWindow", "发送", None))
        self.label_6.setText(_translate("MainWindow", "CMD3:", None))
        self.cmd3sned_Button.setText(_translate("MainWindow", "发送", None))
        self.label_7.setText(_translate("MainWindow", "CMD4:", None))
        self.cmd4sned_Button.setText(_translate("MainWindow", "发送", None))
        self.label_8.setText(_translate("MainWindow", "CMD5:", None))
        self.cmd5sned_Button.setText(_translate("MainWindow", "发送", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.sendtab), _translate("MainWindow", "SendData", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.debugdatatab), _translate("MainWindow", "DebugData", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.matplottab), _translate("MainWindow", "Dataplot", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.motortab), _translate("MainWindow", "Instaspin ", None))
        self.maintabwidget.setTabText(self.maintabwidget.indexOf(self.scitooltab), _translate("MainWindow", "SciTool", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">电机串口调试工具</span></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Instaspin Foc</span>交流群:<span style=\" text-decoration: underline;\">335663930</span><span style=\" font-weight:600;\"> Author</span>@<span style=\" text-decoration: underline;\">nixianmin</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.maintabwidget.setTabText(self.maintabwidget.indexOf(self.about_tab), _translate("MainWindow", "About", None))

