# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scom_ui.ui'
#
# Created: Mon May  4 10:46:03 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MotorDebugTool(object):
    def setupUi(self, MotorDebugTool):
        MotorDebugTool.setObjectName(_fromUtf8("MotorDebugTool"))
        MotorDebugTool.resize(856, 614)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MotorDebugTool.sizePolicy().hasHeightForWidth())
        MotorDebugTool.setSizePolicy(sizePolicy)
        MotorDebugTool.setMinimumSize(QtCore.QSize(856, 570))
        self.centralwidget = QtGui.QWidget(MotorDebugTool)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 350))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.mainlayout = QtGui.QHBoxLayout()
        self.mainlayout.setSpacing(1)
        self.mainlayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.mainlayout.setContentsMargins(0, 0, -1, -1)
        self.mainlayout.setObjectName(_fromUtf8("mainlayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.distext = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distext.sizePolicy().hasHeightForWidth())
        self.distext.setSizePolicy(sizePolicy)
        self.distext.setMaximumSize(QtCore.QSize(194, 16777215))
        self.distext.setTabPosition(QtGui.QTabWidget.North)
        self.distext.setTabShape(QtGui.QTabWidget.Triangular)
        self.distext.setObjectName(_fromUtf8("distext"))
        self.distext1 = QtGui.QWidget()
        self.distext1.setMouseTracking(False)
        self.distext1.setObjectName(_fromUtf8("distext1"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.distext1)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.distextEdit1 = QtGui.QTextEdit(self.distext1)
        self.distextEdit1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distextEdit1.sizePolicy().hasHeightForWidth())
        self.distextEdit1.setSizePolicy(sizePolicy)
        self.distextEdit1.setMaximumSize(QtCore.QSize(189, 16777215))
        self.distextEdit1.setSizeIncrement(QtCore.QSize(0, 0))
        self.distextEdit1.setReadOnly(True)
        self.distextEdit1.setObjectName(_fromUtf8("distextEdit1"))
        self.verticalLayout_7.addWidget(self.distextEdit1)
        self.distext.addTab(self.distext1, _fromUtf8(""))
        self.distext2 = QtGui.QWidget()
        self.distext2.setObjectName(_fromUtf8("distext2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.distext2)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.distringEdit = QtGui.QTextEdit(self.distext2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distringEdit.sizePolicy().hasHeightForWidth())
        self.distringEdit.setSizePolicy(sizePolicy)
        self.distringEdit.setReadOnly(True)
        self.distringEdit.setObjectName(_fromUtf8("distringEdit"))
        self.verticalLayout_10.addWidget(self.distringEdit)
        self.distext.addTab(self.distext2, _fromUtf8(""))
        self.distex3 = QtGui.QWidget()
        self.distex3.setObjectName(_fromUtf8("distex3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.distex3)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setMargin(1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.distex3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.IQBox = QtGui.QSpinBox(self.distex3)
        self.IQBox.setMinimum(1)
        self.IQBox.setMaximum(30)
        self.IQBox.setObjectName(_fromUtf8("IQBox"))
        self.horizontalLayout_2.addWidget(self.IQBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.datadealEdit = QtGui.QTextEdit(self.distex3)
        self.datadealEdit.setReadOnly(True)
        self.datadealEdit.setObjectName(_fromUtf8("datadealEdit"))
        self.verticalLayout_11.addWidget(self.datadealEdit)
        self.distext.addTab(self.distex3, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.distext)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(10, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.comtext = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comtext.sizePolicy().hasHeightForWidth())
        self.comtext.setSizePolicy(sizePolicy)
        self.comtext.setMinimumSize(QtCore.QSize(35, 25))
        self.comtext.setMaximumSize(QtCore.QSize(40, 16777215))
        self.comtext.setMaxLength(1)
        self.comtext.setFrame(True)
        self.comtext.setEchoMode(QtGui.QLineEdit.Normal)
        self.comtext.setAlignment(QtCore.Qt.AlignCenter)
        self.comtext.setObjectName(_fromUtf8("comtext"))
        self.horizontalLayout_4.addWidget(self.comtext)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.combobaudrate = QtGui.QComboBox(self.centralwidget)
        self.combobaudrate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobaudrate.sizePolicy().hasHeightForWidth())
        self.combobaudrate.setSizePolicy(sizePolicy)
        self.combobaudrate.setMinimumSize(QtCore.QSize(0, 25))
        self.combobaudrate.setMaximumSize(QtCore.QSize(110, 16777215))
        self.combobaudrate.setBaseSize(QtCore.QSize(0, 0))
        self.combobaudrate.setEditable(False)
        self.combobaudrate.setObjectName(_fromUtf8("combobaudrate"))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.combobaudrate.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.combobaudrate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.combodatabit = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combodatabit.sizePolicy().hasHeightForWidth())
        self.combodatabit.setSizePolicy(sizePolicy)
        self.combodatabit.setMinimumSize(QtCore.QSize(0, 25))
        self.combodatabit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.combodatabit.setObjectName(_fromUtf8("combodatabit"))
        self.combodatabit.addItem(_fromUtf8(""))
        self.combodatabit.addItem(_fromUtf8(""))
        self.combodatabit.addItem(_fromUtf8(""))
        self.combodatabit.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.combodatabit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.combocheckbit = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combocheckbit.sizePolicy().hasHeightForWidth())
        self.combocheckbit.setSizePolicy(sizePolicy)
        self.combocheckbit.setMinimumSize(QtCore.QSize(0, 25))
        self.combocheckbit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.combocheckbit.setObjectName(_fromUtf8("combocheckbit"))
        self.combocheckbit.addItem(_fromUtf8(""))
        self.combocheckbit.addItem(_fromUtf8(""))
        self.combocheckbit.addItem(_fromUtf8(""))
        self.combocheckbit.addItem(_fromUtf8(""))
        self.combocheckbit.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.combocheckbit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.combostopbit = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combostopbit.sizePolicy().hasHeightForWidth())
        self.combostopbit.setSizePolicy(sizePolicy)
        self.combostopbit.setMinimumSize(QtCore.QSize(0, 25))
        self.combostopbit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.combostopbit.setObjectName(_fromUtf8("combostopbit"))
        self.combostopbit.addItem(_fromUtf8(""))
        self.combostopbit.addItem(_fromUtf8(""))
        self.combostopbit.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.combostopbit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(194, 16777215))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.mainlayout.addLayout(self.verticalLayout_2)
        self.datadealtab = QtGui.QTabWidget(self.centralwidget)
        self.datadealtab.setObjectName(_fromUtf8("datadealtab"))
        self.datadeal = QtGui.QWidget()
        self.datadeal.setObjectName(_fromUtf8("datadeal"))
        self.gridLayout = QtGui.QGridLayout(self.datadeal)
        self.gridLayout.setMargin(1)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.checkBox_x1 = QtGui.QCheckBox(self.datadeal)
        self.checkBox_x1.setObjectName(_fromUtf8("checkBox_x1"))
        self.horizontalLayout_14.addWidget(self.checkBox_x1)
        self.lowx1edit = QtGui.QLineEdit(self.datadeal)
        self.lowx1edit.setMouseTracking(True)
        self.lowx1edit.setInputMask(_fromUtf8(""))
        self.lowx1edit.setMaxLength(6)
        self.lowx1edit.setCursorPosition(3)
        self.lowx1edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lowx1edit.setObjectName(_fromUtf8("lowx1edit"))
        self.horizontalLayout_14.addWidget(self.lowx1edit)
        self.label_14 = QtGui.QLabel(self.datadeal)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.highx1edit = QtGui.QLineEdit(self.datadeal)
        self.highx1edit.setInputMask(_fromUtf8(""))
        self.highx1edit.setMaxLength(6)
        self.highx1edit.setObjectName(_fromUtf8("highx1edit"))
        self.horizontalLayout_14.addWidget(self.highx1edit)
        self.label_9 = QtGui.QLabel(self.datadeal)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_14.addWidget(self.label_9)
        self.offsetx1_spin = QtGui.QSpinBox(self.datadeal)
        self.offsetx1_spin.setMinimum(-99999)
        self.offsetx1_spin.setMaximum(999999)
        self.offsetx1_spin.setObjectName(_fromUtf8("offsetx1_spin"))
        self.horizontalLayout_14.addWidget(self.offsetx1_spin)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.textEdit_x1 = QtGui.QTextEdit(self.datadeal)
        self.textEdit_x1.setReadOnly(True)
        self.textEdit_x1.setObjectName(_fromUtf8("textEdit_x1"))
        self.verticalLayout_9.addWidget(self.textEdit_x1)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkBox_x2 = QtGui.QCheckBox(self.datadeal)
        self.checkBox_x2.setObjectName(_fromUtf8("checkBox_x2"))
        self.horizontalLayout_8.addWidget(self.checkBox_x2)
        self.lowx2edit = QtGui.QLineEdit(self.datadeal)
        self.lowx2edit.setInputMask(_fromUtf8(""))
        self.lowx2edit.setMaxLength(6)
        self.lowx2edit.setObjectName(_fromUtf8("lowx2edit"))
        self.horizontalLayout_8.addWidget(self.lowx2edit)
        self.label_8 = QtGui.QLabel(self.datadeal)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.highx2edit = QtGui.QLineEdit(self.datadeal)
        self.highx2edit.setInputMask(_fromUtf8(""))
        self.highx2edit.setMaxLength(6)
        self.highx2edit.setObjectName(_fromUtf8("highx2edit"))
        self.horizontalLayout_8.addWidget(self.highx2edit)
        self.label_10 = QtGui.QLabel(self.datadeal)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.offsetx2_spin = QtGui.QSpinBox(self.datadeal)
        self.offsetx2_spin.setMinimum(-999999)
        self.offsetx2_spin.setMaximum(999999)
        self.offsetx2_spin.setProperty("value", 20)
        self.offsetx2_spin.setObjectName(_fromUtf8("offsetx2_spin"))
        self.horizontalLayout_8.addWidget(self.offsetx2_spin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.textEdit_x2 = QtGui.QTextEdit(self.datadeal)
        self.textEdit_x2.setReadOnly(True)
        self.textEdit_x2.setObjectName(_fromUtf8("textEdit_x2"))
        self.verticalLayout_5.addWidget(self.textEdit_x2)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_x3 = QtGui.QCheckBox(self.datadeal)
        self.checkBox_x3.setObjectName(_fromUtf8("checkBox_x3"))
        self.horizontalLayout_7.addWidget(self.checkBox_x3)
        self.lowx3edit = QtGui.QLineEdit(self.datadeal)
        self.lowx3edit.setInputMask(_fromUtf8(""))
        self.lowx3edit.setMaxLength(6)
        self.lowx3edit.setFrame(True)
        self.lowx3edit.setObjectName(_fromUtf8("lowx3edit"))
        self.horizontalLayout_7.addWidget(self.lowx3edit)
        self.label_7 = QtGui.QLabel(self.datadeal)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.highx3edit = QtGui.QLineEdit(self.datadeal)
        self.highx3edit.setInputMask(_fromUtf8(""))
        self.highx3edit.setMaxLength(6)
        self.highx3edit.setObjectName(_fromUtf8("highx3edit"))
        self.horizontalLayout_7.addWidget(self.highx3edit)
        self.label_11 = QtGui.QLabel(self.datadeal)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.offsetx3_spin = QtGui.QSpinBox(self.datadeal)
        self.offsetx3_spin.setMinimum(-999999)
        self.offsetx3_spin.setMaximum(999999)
        self.offsetx3_spin.setProperty("value", 40)
        self.offsetx3_spin.setObjectName(_fromUtf8("offsetx3_spin"))
        self.horizontalLayout_7.addWidget(self.offsetx3_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.textEdit_x3 = QtGui.QTextEdit(self.datadeal)
        self.textEdit_x3.setReadOnly(True)
        self.textEdit_x3.setObjectName(_fromUtf8("textEdit_x3"))
        self.verticalLayout_4.addWidget(self.textEdit_x3)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.checkBox_x4 = QtGui.QCheckBox(self.datadeal)
        self.checkBox_x4.setObjectName(_fromUtf8("checkBox_x4"))
        self.horizontalLayout_13.addWidget(self.checkBox_x4)
        self.lowx4edit = QtGui.QLineEdit(self.datadeal)
        self.lowx4edit.setInputMask(_fromUtf8(""))
        self.lowx4edit.setMaxLength(6)
        self.lowx4edit.setObjectName(_fromUtf8("lowx4edit"))
        self.horizontalLayout_13.addWidget(self.lowx4edit)
        self.label_13 = QtGui.QLabel(self.datadeal)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.highx4edit = QtGui.QLineEdit(self.datadeal)
        self.highx4edit.setInputMask(_fromUtf8(""))
        self.highx4edit.setMaxLength(6)
        self.highx4edit.setObjectName(_fromUtf8("highx4edit"))
        self.horizontalLayout_13.addWidget(self.highx4edit)
        self.label_12 = QtGui.QLabel(self.datadeal)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_13.addWidget(self.label_12)
        self.offsetx4_spin = QtGui.QSpinBox(self.datadeal)
        self.offsetx4_spin.setMinimum(-999999)
        self.offsetx4_spin.setMaximum(999999)
        self.offsetx4_spin.setObjectName(_fromUtf8("offsetx4_spin"))
        self.horizontalLayout_13.addWidget(self.offsetx4_spin)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.textEdit_x4 = QtGui.QTextEdit(self.datadeal)
        self.textEdit_x4.setReadOnly(True)
        self.textEdit_x4.setObjectName(_fromUtf8("textEdit_x4"))
        self.verticalLayout_8.addWidget(self.textEdit_x4)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.datadealtab.addTab(self.datadeal, _fromUtf8(""))
        self.matplottab = QtGui.QWidget()
        self.matplottab.setObjectName(_fromUtf8("matplottab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.matplottab)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setMargin(1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSpacing(1)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.verticalLayout_14.setStretch(0, 4)
        self.verticalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.datadealtab.addTab(self.matplottab, _fromUtf8(""))
        self.multiPlot = QtGui.QWidget()
        self.multiPlot.setObjectName(_fromUtf8("multiPlot"))
        self.multplotLayout = QtGui.QHBoxLayout(self.multiPlot)
        self.multplotLayout.setObjectName(_fromUtf8("multplotLayout"))
        self.datadealtab.addTab(self.multiPlot, _fromUtf8(""))
        self.mainlayout.addWidget(self.datadealtab)
        self.mainlayout.setStretch(1, 5)
        self.verticalLayout_15.addLayout(self.mainlayout)
        MotorDebugTool.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MotorDebugTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MotorDebugTool.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MotorDebugTool)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MotorDebugTool.setStatusBar(self.statusbar)
        self.clrdata_action = QtGui.QAction(MotorDebugTool)
        self.clrdata_action.setCheckable(False)
        self.clrdata_action.setObjectName(_fromUtf8("clrdata_action"))
        self.menu.addAction(self.clrdata_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MotorDebugTool)
        self.distext.setCurrentIndex(1)
        self.combobaudrate.setCurrentIndex(16)
        self.datadealtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MotorDebugTool)

    def retranslateUi(self, MotorDebugTool):
        MotorDebugTool.setWindowTitle(_translate("MotorDebugTool", "MotorDebugTool", None))
        self.distext.setTabText(self.distext.indexOf(self.distext1), _translate("MotorDebugTool", "Hex", None))
        self.distext.setTabText(self.distext.indexOf(self.distext2), _translate("MotorDebugTool", "String", None))
        self.label_6.setText(_translate("MotorDebugTool", "IQ number:", None))
        self.distext.setTabText(self.distext.indexOf(self.distex3), _translate("MotorDebugTool", "Data Deal IQ", None))
        self.label_2.setText(_translate("MotorDebugTool", "端口号：", None))
        self.lineEdit.setText(_translate("MotorDebugTool", "Com Port", None))
        self.comtext.setInputMask(_translate("MotorDebugTool", "9; ", None))
        self.comtext.setText(_translate("MotorDebugTool", "3", None))
        self.label.setText(_translate("MotorDebugTool", "波特率：", None))
        self.combobaudrate.setItemText(0, _translate("MotorDebugTool", "50", None))
        self.combobaudrate.setItemText(1, _translate("MotorDebugTool", "75", None))
        self.combobaudrate.setItemText(2, _translate("MotorDebugTool", "110", None))
        self.combobaudrate.setItemText(3, _translate("MotorDebugTool", "134", None))
        self.combobaudrate.setItemText(4, _translate("MotorDebugTool", "150", None))
        self.combobaudrate.setItemText(5, _translate("MotorDebugTool", "200", None))
        self.combobaudrate.setItemText(6, _translate("MotorDebugTool", "300", None))
        self.combobaudrate.setItemText(7, _translate("MotorDebugTool", "600", None))
        self.combobaudrate.setItemText(8, _translate("MotorDebugTool", "1200", None))
        self.combobaudrate.setItemText(9, _translate("MotorDebugTool", "1800", None))
        self.combobaudrate.setItemText(10, _translate("MotorDebugTool", "2400", None))
        self.combobaudrate.setItemText(11, _translate("MotorDebugTool", "4800", None))
        self.combobaudrate.setItemText(12, _translate("MotorDebugTool", "9600", None))
        self.combobaudrate.setItemText(13, _translate("MotorDebugTool", "19200", None))
        self.combobaudrate.setItemText(14, _translate("MotorDebugTool", "38400", None))
        self.combobaudrate.setItemText(15, _translate("MotorDebugTool", "57600", None))
        self.combobaudrate.setItemText(16, _translate("MotorDebugTool", "115200", None))
        self.label_3.setText(_translate("MotorDebugTool", "数据位：", None))
        self.combodatabit.setItemText(0, _translate("MotorDebugTool", "8bit", None))
        self.combodatabit.setItemText(1, _translate("MotorDebugTool", "7bit", None))
        self.combodatabit.setItemText(2, _translate("MotorDebugTool", "6bit", None))
        self.combodatabit.setItemText(3, _translate("MotorDebugTool", "5bit", None))
        self.label_4.setText(_translate("MotorDebugTool", "校验位：", None))
        self.combocheckbit.setItemText(0, _translate("MotorDebugTool", "None无", None))
        self.combocheckbit.setItemText(1, _translate("MotorDebugTool", "Even偶", None))
        self.combocheckbit.setItemText(2, _translate("MotorDebugTool", "Odd奇", None))
        self.combocheckbit.setItemText(3, _translate("MotorDebugTool", "Mark1", None))
        self.combocheckbit.setItemText(4, _translate("MotorDebugTool", "Space0", None))
        self.label_5.setText(_translate("MotorDebugTool", "停止位：", None))
        self.combostopbit.setItemText(0, _translate("MotorDebugTool", "1bit", None))
        self.combostopbit.setItemText(1, _translate("MotorDebugTool", "1.5bit", None))
        self.combostopbit.setItemText(2, _translate("MotorDebugTool", "2bit", None))
        self.pushButton.setText(_translate("MotorDebugTool", "打开", None))
        self.checkBox_x1.setText(_translate("MotorDebugTool", "范围1:", None))
        self.lowx1edit.setText(_translate("MotorDebugTool", "-10", None))
        self.label_14.setText(_translate("MotorDebugTool", " < X1 < ", None))
        self.highx1edit.setText(_translate("MotorDebugTool", "10", None))
        self.label_9.setText(_translate("MotorDebugTool", "Offset:", None))
        self.checkBox_x2.setText(_translate("MotorDebugTool", "范围2:", None))
        self.lowx2edit.setText(_translate("MotorDebugTool", "10", None))
        self.label_8.setText(_translate("MotorDebugTool", " < X2 < ", None))
        self.highx2edit.setText(_translate("MotorDebugTool", "30", None))
        self.label_10.setText(_translate("MotorDebugTool", "Offset:", None))
        self.checkBox_x3.setText(_translate("MotorDebugTool", "范围3:", None))
        self.lowx3edit.setText(_translate("MotorDebugTool", "30", None))
        self.label_7.setText(_translate("MotorDebugTool", " < X3 < ", None))
        self.highx3edit.setText(_translate("MotorDebugTool", "50", None))
        self.label_11.setText(_translate("MotorDebugTool", "Offset:", None))
        self.checkBox_x4.setText(_translate("MotorDebugTool", "范围4:", None))
        self.label_13.setText(_translate("MotorDebugTool", " < X4 < ", None))
        self.label_12.setText(_translate("MotorDebugTool", "Offset:", None))
        self.datadealtab.setTabText(self.datadealtab.indexOf(self.datadeal), _translate("MotorDebugTool", "DataDeal", None))
        self.datadealtab.setTabText(self.datadealtab.indexOf(self.matplottab), _translate("MotorDebugTool", "MatPlot", None))
        self.datadealtab.setTabText(self.datadealtab.indexOf(self.multiPlot), _translate("MotorDebugTool", "multiPlot", None))
        self.menu.setTitle(_translate("MotorDebugTool", "Action", None))
        self.clrdata_action.setText(_translate("MotorDebugTool", "Clear display data", None))

